const menu = [
  {
    id: 1,
    title: 'Stracciatella',
    ingredients: 'Vispad burrata, granatäpple, grillade vindruvor, pistagenötter, chili & brödsmulor',
    price: 119,
    category: 'Adults',
    LactoseFree: false,
  },
  {
    id: 11,
    title: 'Caprese',
    ingredients: 'Burratina, solmogna tomater, lagrad balsamico, peperoncino & basilika',
    price: 109,
    category: 'Adults',
    LactoseFree: false,
  },
  {
    id: 12,
    title: 'Bruschettone pomodoro e bufala',
    ingredients: 'Nybakat bröd toppas med handplockade tomater, buffelmozzarella & färsk basilika',
    price: 129,
    category: 'Adults',
    LactoseFree: false,
  },
  {
    id: 13,
    title: 'Carpaccio di manzo',
    ingredients: 'Oxfilé, löjrom, tryffel, parmesan, picklad rödlök, kapris & dijon',
    price: 145,
    category: 'Adults',
    LactoseFree: false,
  },
  {
    id: 14,
    title: 'Carciofi',
    ingredients: 'Friterad kronärtskocka, parmesan, limoncellokräm & rostade jordnötter',
    price: 89,
    category: 'Adults',
    LactoseFree: false,
  },
  {
    id: 15,
    title: 'Ravioli ai funghi porcini',
    ingredients: 'Ravioli fylld med Karl-Johansvamp, skogssvamp & parmesansås',
    price: 159,
    category: 'Adults',
    LactoseFree: false,
  },
  {
    id: 16,
    title: 'Linguine al pesto e burratina',
    ingredients: 'Linguine, krämig pesto, vispad burratina & pistagenötter',
    price: 159,
    category: 'Adults',
    LactoseFree: true,
  },
  {
    id: 17,
    title: 'Spaghetti alla carbonara',
    ingredients: 'Spaghetti, pancetta, äggula & parmesansås',
    price: 155,
    category: 'Adults',
    LactoseFree: true,
  },
  {
    id: 18,
    title: 'Salsiccia piccante',
    ingredients: 'Rigatoni, stark salsiccia, tomatsås, syrad grädde, cocktailtomater, chili & parmesan',
    price: 165,
    category: 'Adults',
    LactoseFree: true,
  },
  {
    id: 19,
    title: 'Filetto di manzo',
    ingredients: 'Tagliatelle, oxfilé, tryffel & skogsvamp',
    price: 209,
    category: 'Adults',
    LactoseFree: false,
  },
  //Children
  {
    id: 20,
    title: 'Pankaka',
    ingredients: 'Pankaka, grädde, jordgubbsylt',
    price: 95,
    category: 'Children',
    LactoseFree: false,
  },
  {
    id: 21,
    title: 'Köttbullar & mos',
    ingredients: 'Köttbullar, gräddsås, lingonsylt, mos',
    price: 105,
    category: 'Children',
    LactoseFree: false,
  },
  {
    id: 22,
    title: 'Köttfärsås & spagetti',
    ingredients: 'Köttfärsås, spagetti, toppat med parmesan',
    price: 85,
    category: 'Children',
    LactoseFree: false,
  },
  {
    id: 23,
    title: 'Hamburgare',
    ingredients: '100g Hamburgare, pommes frites, dressing',
    price: 99,
    category: 'Children',
    LactoseFree: true,
  },
  {
    id: 24,
    title: 'Korv med mos',
    ingredients: '2st grillkorvar med egengjort mos.',
    price: 110,
    category: 'Children',
    LactoseFree: false,
  },
  {
    id: 25,
    title: 'Kebabtallrik',
    ingredients: 'Kebabkött, pommes frites, sås, sallad',
    price: 75,
    category: 'Children',
    LactoseFree: true,
  },
  {
    id: 26,
    title: 'Margherita',
    ingredients: 'Tomatsås, Mozzarellaost',
    price: 89,
    category: 'Children',
    LactoseFree: false,
  },
  {
    id: 27,
    title: 'Vesuvio',
    ingredients: 'Tomatsås, Mozzarellaost, Skinka',
    price: 119,
    category: 'Children',
    LactoseFree: true,
  },
  {
    id: 28,
    title: 'Al Funghi',
    ingredients: 'Tomatsås, Mozzarellaost, Champinjoner (Färska)',
    price: 105,
    category: 'Children',
    LactoseFree: true,
  },
  {
    id: 29,
    title: 'Fish & Chips',
    ingredients: 'Sprödbakad tors med pommes frites, sås, sallad',
    price: 95,
    category: 'Children',
    LactoseFree: false,
  },
  //Couple
  {
    id: 30,
    title: 'Eldad Lax',
    ingredients: 'Salad nicoise, sparris, trädgårdstomater, machesallad, cirkulerat ägg, sugarsnaps, nobisdressing',
    price: 189,
    category: 'Couple',
    LactoseFree: false,
  },
  {
    id: 31,
    title: 'Mojo Råbiff',
    ingredients: 'Nötinnanlår från närke, rödbetor, kapris, pepparrot, Dijonaise, krispig potatis, syrad charlottenlök',
    price: 168,
    category: 'Couple',
    LactoseFree: false,
  },
  {
    id: 32,
    title: 'Kyoto Sandwich',
    ingredients: 'Fläskschnitzel, spetskål, melon rättika, gochujang, tonkatsusås, crystal bread',
    price: 178,
    category: 'Couple',
    LactoseFree: false,
  },
  {
    id: 33,
    title: 'Koreansk BBQ-kyckling',
    ingredients: 'Serveras med säsongens sallad',
    price: 169,
    category: 'Couple',
    LactoseFree: false,
  },
  {
    id: 34,
    title: 'Flankstek sliders x2',
    ingredients: 'Briochebröd, caesardressing, gemsallad, picklad gurka, lökringar, JB`s BBQ-sås',
    price: 179,
    category: 'Couple',
    LactoseFree: false,
  },
  {
    id: 35,
    title: 'Coconut Moules',
    ingredients: 'Blåmusslor, kokosgrädde, citrongräs, chilli, ingefära, limeblad, räkchips',
    price: 168,
    category: 'Couple',
    LactoseFree: true,
  },
  {
    id: 36,
    title: 'Pasta frutti di mare',
    ingredients: 'Linguine, pilgrimsmusslor, scampi, bläckfisk, blåmusslor, vitt vin, tomat, basilika',
    price: 208,
    category: 'Couple',
    LactoseFree: true,
  },
  {
    id: 37,
    title: 'Balinese shish kebab',
    ingredients: 'Marinerad kycklingspett, melonsallad, limeyoghurt, mango chutney, sötpotatis krisp',
    price: 195,
    category: 'Couple',
    LactoseFree: true,
  },
  {
    id: 38,
    title: 'Färsk fjällröding',
    ingredients: 'Sparris & ramslöksrisotto, dillpesto, torkade olivsmulor, sommarcrudité',
    price: 239,
    category: 'Couple',
    LactoseFree: false,
  },
  {
    id: 39,
    title: 'Oxfilé delux',
    ingredients: 'Oxfilé från lokalt slakteri, potatismos, bea',
    price: 249,
    category: 'Couple',
    LactoseFree: true,
  },
];

export default menu;
